version: "3.8"
services:
  frontend:
    build:
      context: ./promo-code-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_PROMO_CODE_SERVICE_URL=http://localhost:5184/promoCodeHub
    volumes:
      - ./promo-code-client:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: ["npm", "start"]